version: 3.8

services:
  user-services:
    build:
      context: ./user-services
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file::
      - .env
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  