version: "3.8"

services:
  user-services:
    build:
      context: ./user-services
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - user-services/.env
    depends_on:
      - mongo
    networks:
      - ecommerce-network
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ecommerce-network

  product-services:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - product-service/.env
    depends_on:
      - mongo
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

  
